# Generated by Django 5.0.7 on 2024-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
